'use client';
import './globals.css'
import { ThemeProvider, createTheme } from '@mui/material/styles';

// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

const darkTheme = createTheme({
    palette: {
        mode: 'dark',
    },
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <ThemeProvider theme={darkTheme}>
                    {children}
                </ThemeProvider>
            </body>
        </html>
    )
}
